
#
development:
  adapter: postgresql
  encoding: unicode
  database: travelApp_dev
  pool: 5
  username: phillipjones
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: travelApp_test
  pool: 5
  username: phillipjones
  password:
